### PR TITLE
Tidied up gemfile on `still`

### PR DESCRIPTION
**Pull request by luke-hill**
## Summary

Tidy up of Gemfile on `still` branch

## Motivation and Context

Easier to fix up / triage `still` issues

## How Has This Been Tested?

CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactoring (cleanup of codebase without changing any existing functionality)
- [ ] Update documentation

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by luke-hill** [comment]
I've rebased this with the latest `still` was about 20 commits behind.

If you can take a look at this soon @mvz and let me know if we can merge it. Trying to check up on all my outstanding cucumber PR's (As I've got about 10 across all the codebases)

**Comment by mvz** [comment]
There are a lot of build failures with this change. Some of the errors are due to RVM so :man_shrugging:, but on 1.9.3 at least there are dependency problems.

I really like how this cleans things up, but I don't know if we can fix these build failures.

**Comment by luke-hill** [comment]
Is this something this PR has caused? It shouldn't have caused any issues tbh..?

**Comment by mvz** [comment]
> Is this something this PR has caused?

Yes, I think so, at least for the 1.8.7 and 1.9.2 builds.

**Comment by luke-hill** [comment]
Ok I've found out that historically a lot of gems that worked on 1.8.7 or the 1.x series had huge issues interoperably with other ruby versions.

As such I'm going to change this PR to raise the minimum ruby reqt to 2.0 and that'll allow me to simplify a load of the functionality. Hope that's ok @mvz as it gives us a "small" interim update for the 0.14.x series of aruba which will be needed in stages to help people get into the 2.3 requirement they'll need for the 1.x series.

**Comment by luke-hill** [comment]
I've just re-checked this against the latest `still` and this has the same ratio of passing/failing tests. So if it's ok with you I'd like to merge this in, as it's a big win. And then we can tackle stabilising `still` up again.

WDYT @mvz ?

**Comment by mvz** [comment]
I don't want to drop compatibility with Ruby 1.8 in the 0.14.x series.

**Comment by luke-hill** [comment]
Oki. I'll probably close this for now and re-visit it. It's getting quite tricky to try make bits of this work. Too many moving parts in the Gemfile. I think if you're gonna go from ruby 1.8 -> ruby 2.3 then i'll just focus on making the `master` branch better

**Pull request closed without merging**
