### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by mvz**
## Summary

Update several development dependencies.

## Motivation and Context

Keep things up to date.

### CODE REVIEW

**Comment by olleolleolle** [comment]
@mvz Can we move to latest jruby-9.1.17.0 (in the 9.1.x.x series)?

Or, directly to latest release jruby-9.2.5.0? (Have we even tried?)

**Comment by mvz** [comment]
Yes, moving to latest jruby should be possible.

**Comment by mvz** [comment]
I'll update the other Rubies to their latest point release as well.

**Comment by mvz** [comment]
@olleolleolle Done!

**Pull request merged**
