### PR TITLE
Allow newer versions of Cucumber

### PR DESCRIPTION
**Pull request by mattwynne**
This allows us to test / release new versions of Cucumber without first having to come here to make a new release of Arubua.
    
I think the only reason to cap the max version would be if we knew there was a backwards-compatibility problem with a release of Cucumber, but there isn't, so I think we can safely just remove it?

### CODE REVIEW

**Comment by mvz** [comment]
I'm not a big fan of open-ended dependencies: If Cucumber releases a new major version, it _may_ break Aruba. On the other hand, since Cucumber uses Aruba for its own tests, that is not very likely at the moment.

What would be other possible ways to solve the problem?

**Comment by aurelien-reeves** [comment]
> 
> 
> I'm not a big fan of open-ended dependencies: If Cucumber releases a new major version, it _may_ break Aruba. On the other hand, since Cucumber uses Aruba for its own tests, that is not very likely at the moment.
> 
> What would be other possible ways to solve the problem?

Actually, at the moment, we cannot release a new version of cucumber because of aruba.
We could, but we cannot execute tests before releasing it.

I share the thinking of @mattwynne: while everything is working fine, having an open-ended dependency is not an issue.
If some day cucumber break aruba, we can release a patched version of aruba to restrict the usage of some specific version of cucumber, then work on a minor or major new release to fix the issue we would face with that new cucumber.

What do you think?

**Comment by mvz** [comment]
> while everything is working fine, having an open-ended dependency is not an issue.

Of course. I have an issue with the case where not everything is fine :slightly_smiling_face:. Maybe I can bump the max version to "< 7.0" and perhaps even test with cucumber's master branch?

**Comment by aurelien-reeves** [comment]
> 
> 
> > while everything is working fine, having an open-ended dependency is not an issue.
> 
> Of course. I have an issue with the case where not everything is fine 🙂. Maybe I can bump the max version to "< 7.0" and perhaps even test with cucumber's master branch?

Bumping to version < 7.0 would actually result in the exact same risk, but less future-proof:

Cucumber version 6.0 actually does not exists yet. Maybe aruba is not compatible with it, we just don't know yet, and we won't until cucumber@6 is released.

Having some tests which uses cucumber's master branch would help us to detect issues before any releases.

**Review by mvz — APPROVED** [review]

**Comment by aurelien-reeves** [comment]
In order to be able to move-on with our actual release of cucumber-wire and cucumber, we have decided to keep an upper-bound version number here and to continue the discussion there: https://github.com/cucumber/aruba/issues/729

**Pull request merged**
