### PR TITLE
Move Build Status Badge to top of the README page.

### PR DESCRIPTION
**Pull request by junaruga**
## Summary

Move Build Status Badge to top of the README page.

## Motivation and Context

Right now build status is in the bottom of the `README.md`.
This style has been seen by https://github.com/rails/rails

However, other projects in cucumber have the build status on the top of `README.md`.
such as
https://github.com/cucumber/cucumber-ruby/blob/master/README.md
https://github.com/junaruga/cucumber-ruby-core/blob/master/README.md
https://github.com/cucumber/gherkin-ruby/blob/master/README.md

This style's merit is that people can see the status easily without scroll down.
I think that this style promotes contribution to pass tests.

You can see modified README here.
https://github.com/junaruga/aruba/blob/feature/build-status-badge-on-top/README.md

By the way,
https://ci.appveyor.com/project/cucumberbdd/aruba/branch/still
> Build not found or access denied.

Appveyor does not have still branch?

Appveryor has an custom test on build status image.
https://www.appveyor.com/blog/2014/11/26/customizing-text-of-build-status-badges/
Travis does not have the custom text.
https://github.com/travis-ci/travis-ci/issues/5037

This image URL that is currently used in `still` branch is not right.
This image may be for master branch.
https://ci.appveyor.com/api/projects/status/jfo2tkqhnrqqcivl?svg=true

## How Has This Been Tested?

Checked modified README.
But I want to ask you about the detail design.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Refactoring (cleanup of codebase withouth changing any existing functionality)
- [ ] Update documentation

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by junaruga** [comment]
@olleolleolle ok I will add the link.

> By the way,
> https://ci.appveyor.com/project/cucumberbdd/aruba/branch/still
>    Build not found or access denied.
> Appveyor does not have still branch?

By the way, do you know the detail of above thing?
This shows that "still" branch is not used by Appveror. Is it correct?
If do that, we can remove the Appveror badge image for still branch.

**Comment by junaruga** [comment]
Rebased and squashed!

**Comment by maxmeyer** [comment]
@junaruga I think it makes sense to have the `still` branch available on all build services. The appveyor part is not the best maintained one.

**Comment by maxmeyer** [comment]
@junaruga I see your point in making the build status available on first sight, but personally I prefer to the table layout as it appears to be more readable.

@olleolleolle We had this kind of layout for the build badges already and I introduced the new one with purpose.

Maybe there's a good solution which combines pros of both version.

In the current version - as a "newcomer" I would not be able to see, what badge is refering to what service. I think even using "master" and "still" are not the best choices - I made - for the table heading.

### New
new

### Old
old

**Comment by junaruga** [comment]
> In the current version - as a "newcomer" I would not be able to see, what badge is refering to what service.

So, how about this?
https://github.com/cucumber/cucumber-ruby/blob/master/README.md
Is this page's CI image badge readable for you or not?

Ah you are a newcomer? I did not know that.

**Pull request merged**
