### PR TITLE
Drop unsupported rubies

### PR DESCRIPTION
**Pull request by maxmeyer**
## Summary

This PR drops supported for unsupported rubies from 1.0.0 on.

### CODE REVIEW

**Comment by mattwynne** [comment]
Did you run this past @myronmarston? Those of us maintaining test frameworks like to be able to support our users on older Rubies. I think this will mean RSpec and Cucumber won't be able to use Aruba 1.0.

**Comment by myronmarston** [comment]
> I think this will mean RSpec and Cucumber won't be able to use Aruba 1.0.

That's true if we wanted to use Aruba 1.0 in RSpec's test suite for RSpec 3.x.  But in RSpec 4 we'll be dropping old ruby versions, too (probably 1.8.7 and 1.9.2 like you've done here) so we can just wait to upgrade to Aruba 1.0 until that point.  The old version of aruba we are on is meeting our needs just fine :).

**Comment by mattwynne** [comment]
Sweet!

Ref #363

**Comment by maxmeyer** [comment]
I dropped support for rubies < 1.9.3. Cucumber 2 requires > 1.9.3, correct?

I had in mind that Myron wants to drop old ruby support in the upcoming major release and that he's "fine" with version dropping in major versions in aruba.

I think, the 1.0.0 release will be a major clean up + repair release. I really want to get rid of the deprecated code which is still part of aruba for months, sometimes even years.



Am 29. April 2016 20:16:36 MESZ, schrieb Matt Wynne <notifications@github.com>:

**Pull request merged**
