### PR TITLE
Bugfix/to h cast failing on proc call

### PR DESCRIPTION
**Pull request by luke-hill**
## Summary

Fix https://github.com/cucumber/aruba/issues/563

## Details

The casting was failing when certain situations (nil / blank), was being met. As such just performing a quick type check with a safe cast will fix this small bug.

## How Has This Been Tested?

Additional feature test has been added to check for this with a small ruby script

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (cleanup of codebase without changing any existing functionality)
- [ ] Update documentation

## Checklist:

- [x] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Specifically we shouldn't elude to this change being done. Because we don't want people un-knowingly using a type-safe check for hashes, unless they want it (i.e. use ActiveSupport instead)

### CODE REVIEW

**Comment by mvz** [comment]
I'm not that keen on adding a monkey-patch on Object for this. Rather, we should investigate where this `NotImplementedError` comes from and fix that.

**Comment by luke-hill** [comment]
This isn't a monkeypatch. It uses a new safe method which doesn't overload anything.

If you want me to move where this is exposed I can do that? But yeh :confused: 

Also the place it's required has also been fixed. (As per the build passing this step)

**Comment by luke-hill** [comment]
Is this GtM @mvz?

**Comment by mvz** [comment]
I'll take another look when temperatures have dropped below 30 here :-).

**Comment by mvz** [comment]
I've taken a look at the feature file and it succeeds with and without the rest of this pull request. I also saw that `@announce` prints the whole Ruby binary, which is confusing to say the least :laughing:.

I'd like to do the following:
* The `command_content` announcer should not dump the entire command if it's a binary (not related to #563 but still relevant because the current behavior makes it super-hard to see what's going on).
* Instead of returning NotImplementedError, we should raise it.
* We should have a scenario that tests the combination of `@announce` and `@debug`, like `features/03_testing_frameworks/cucumber/announce_information_for_troubleshooting.feature` and `features/03_testing_frameworks/cucumber/steps/command/debug_your_command_in_aruba.feature` combined. This should now fail with a NotImplementedError exception, rather than a NoMethodError.
* The announcer should catch NotImplementedError and output a friendly warning that it cannot announce whatever it wanted to announce.

**Comment by luke-hill** [comment]
:man_shrugging: that sounds quite complex and I'm not sure what that involves in doing.

As this PR fixes the issue, is this sufficient to merge in as is. Or does it destroy some other functionaltiy?

The Extra Test I think was to demonstrate some extra functionality aside from this which was helping me fix it.

I don't mind which approach we take here. Just that most of what you've suggested to me sounds a bit complex and might take up your time already which is swamped with stuff to do.

**Comment by mvz** [comment]
I've decided to implement https://github.com/cucumber/aruba/pull/649#issuecomment-516865997 instead (except for the first point).

**Pull request closed without merging**
