### PR TITLE
Fix dependency error for install

### PR DESCRIPTION
**Pull request by junaruga**
## Summary

Aruba install for development was failed on Ruby 2.4.0.
After updating runtime dependency of cucumber, unit tests are still failed.
However I would like to share the situation.

## Details

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

$ bundle -v
Bundler version 1.14.3

$ bundle install --path vendor/bundle
...
Resolving dependencies...
Bundler could not find compatible versions for gem "gherkin":
  In Gemfile:
    gherkin (~> 4.0)

    gherkin (~> 4.0)

    aruba was resolved to 0.14.1, which depends on
      cucumber (~> 2.3.0) was resolved to 2.3.0, which depends on
        gherkin (~> 3.2.0)
...
```

After updating `aruba.gemspec`, and installing again.

rspec tests were succeeded.

```
$ bundle exec rake test:rspec
356 examples, 0 failures
```

cucumber tests were failed.

```
$ bundle exec rake test:cucumber
...
# /home/jaruga/git/aruba/lib/aruba/cucumber/command.rb:13
      +      Command "cli" not found in PATH-variable "/home/jaruga/git/aruba/tmp/aruba/cli-app/bin:/home/jaruga/git/aruba/tmp/aruba/cli-app/exe:/home/jaruga/git/aruba/vendor/bundle/ruby/2.4.0/bin:/home/jaruga/git/aruba/bin:/home/jaruga/git/aruba/exe:/home/jaruga/git/gem2rpm/bin:/usr/local/valgrind-3.11.0/bin:/usr/local/python-3.6.0/bin:/usr/local/python-2.7.13/bin:/usr/local/ruby-2.4.0/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/home/jaruga/bin". (Aruba::LaunchError)
...
428 scenarios (160 failed, 1 skipped, 267 passed)
1977 steps (160 failed, 51 skipped, 1766 passed)
```

## Motivation and Context

I want to develop and test on Ruby 2.4.0.
This PR's purpose is also to share the result of the `cucumber` tests failures on Travis's result.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by maxmeyer** [comment]
Not sure, why this fails. I think this needs some more investigation. Can you try and use this instructions to debug the "situation"?

https://github.com/cucumber/aruba/blob/master/features/testing_frameworks/cucumber/steps/command/debug.feature

**Comment by junaruga** [comment]
@maxmeyer thanks for the replying. sorry for my late replying.
I would check it next week.

**Comment by junaruga** [comment]
@maxmeyer 

When I ran for specified failed feature file,

```
$ bundle exec cucumber features/api/command/run.feature:26
...
    Then the specs should all pass                       # lib/aruba/cucumber/testing_frameworks.rb:32
      expected "\nRun command\n  example at ./spec/run_spec.rb:5 (FAILED - 1)\n\nFailures:\n\n  1) Run command \n     Failure/Error: before(:each) { run('cli') }\n\n     Aruba::LaunchError:\n       Command \"cli\" not found in PATH-variable \"/home/jaruga/git/aruba/tmp/aruba/cli-app/bin:/home/jaruga/git/aruba/tmp/aruba/cli-app/exe:/home/jaruga/git/aruba/vendor/bundle/ruby/2.4.0/bin:/home/jaruga/git/aruba/bin:/home/jaruga/git/aruba/exe:/home/jaruga/git/gem2rpm/bin:/home/jaruga/git/rpmlint/dist/usr/bin:/usr/local/valgrind-3.11.0/bin:/usr/local/python-3.6.0/bin:/usr/local/ruby-2.4.0/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/home/jaruga/bin\".\n     # /home/jaruga/git/aruba/lib/aruba/processes/spawn_process.rb:253:in `command_string'\n     # /home/jaruga/git/aruba/lib/aruba/processes/spawn_process.rb:60:in `start'\n     # /home/jaruga/git/aruba/lib/aruba/command.rb:67:in `start'\n     # /home/jaruga/git/aruba/lib/aruba/api/command.rb:213:in `run'\n     # ./spec/run_spec.rb:4:in `block (2 levels) in <top (required)>'\n     # /home/jaruga/git/aruba/lib/aruba/rspec.rb:23:in `block (2 levels) in <top (required)>'\n\nFinished in 0.00373 seconds (files took 0.12273 seconds to load)\n1 example, 1 failure\n\nFailed examples:\n\nrspec ./spec/run_spec.rb:5 # Run command " to string includes: "0 failures"
      Diff:
      @@ -1,2 +1,25 @@
      -0 failures
      +
      +Run command
      +  example at ./spec/run_spec.rb:5 (FAILED - 1)
      +
      +Failures:
      +
      +  1) Run command 
      +     Failure/Error: before(:each) { run('cli') }
      +
      +     Aruba::LaunchError:
      +       Command "cli" not found in PATH-variable "/home/jaruga/git/aruba/tmp/aruba/cli-app/bin:/home/jaruga/git/aruba/tmp/aruba/cli-app/exe:/home/jaruga/git/aruba/vendor/bundle/ruby/2.4.0/bin:/home/jaruga/git/aruba/bin:/home/jaruga/git/aruba/exe:/home/jaruga/git/gem2rpm/bin:/home/jaruga/git/rpmlint/dist/usr/bin:/usr/local/valgrind-3.11.0/bin:/usr/local/python-3.6.0/bin:/usr/local/ruby-2.4.0/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/home/jaruga/bin".
      +     # /home/jaruga/git/aruba/lib/aruba/processes/spawn_process.rb:253:in `command_string'
      +     # /home/jaruga/git/aruba/lib/aruba/processes/spawn_process.rb:60:in `start'
      +     # /home/jaruga/git/aruba/lib/aruba/command.rb:67:in `start'
      +     # /home/jaruga/git/aruba/lib/aruba/api/command.rb:213:in `run'
      +     # ./spec/run_spec.rb:4:in `block (2 levels) in <top (required)>'
      +     # /home/jaruga/git/aruba/lib/aruba/rspec.rb:23:in `block (2 levels) in <top (required)>'
      +
      +Finished in 0.00373 seconds (files took 0.12273 seconds to load)
      +1 example, 1 failure
      +
      +Failed examples:
      +
      +rspec ./spec/run_spec.rb:5 # Run command 
       (RSpec::Expectations::ExpectationNotMetError)
      ./lib/aruba/cucumber/command.rb:186:in `/^(?:the )?(output|stderr|stdout)(?: from "([^"]*)")? should( not)? contain( exactly)? "([^"]*)"$/'
      ./lib/aruba/cucumber/testing_frameworks.rb:42:in `/^the spec(?:s)? should( not)?(?: all)? pass(?: with (\d+) failures?)?$/'
      features/api/command/run.feature:42:in `Then the specs should all pass'

Failing Scenarios:
cucumber features/api/command/run.feature:26 # Scenario: Existing executable
```

I think this might be related to my bundle install command, `bundle install --path vendor/bundle`, as Travis Linux tests are all passed.

```
$ find . -name cli
./vendor/bundle/ruby/2.4.0/gems/yard-0.9.8/spec/cli
./vendor/bundle/ruby/2.4.0/gems/yard-0.9.8/lib/yard/cli
./vendor/bundle/ruby/2.4.0/gems/bundler-1.14.6/lib/bundler/cli
./vendor/bundle/ruby/2.4.0/gems/license_finder-2.0.4/spec/lib/license_finder/cli
./vendor/bundle/ruby/2.4.0/gems/license_finder-2.0.4/lib/license_finder/cli
./vendor/bundle/ruby/2.4.0/gems/cucumber-2.3.3/spec/cucumber/cli
./vendor/bundle/ruby/2.4.0/gems/cucumber-2.3.3/features/docs/cli
./vendor/bundle/ruby/2.4.0/gems/cucumber-2.3.3/lib/cucumber/cli
./vendor/bundle/ruby/2.4.0/gems/aruba-0.14.2/features/cli
./vendor/bundle/ruby/2.4.0/gems/aruba-0.14.2/fixtures/cli-app/bin/cli
./vendor/bundle/ruby/2.4.0/gems/aruba-0.14.2/fixtures/cli-app/lib/cli
./vendor/bundle/ruby/2.4.0/gems/aruba-0.14.2/fixtures/empty-app/lib/cli
./tmp/aruba/cli-app/lib/cli
./features/cli
./fixtures/cli-app/lib/cli
./fixtures/empty-app/lib/cli
```

**Comment by mvz** [comment]
@junaruga the Travis build succeeds even if the scenarios fail, unfortunately.

**Comment by junaruga** [comment]
@mvz ok thanks for sharing the fact.

**Pull request merged**
