### PR TITLE
Release 1.0.0.alpha3

### PR DESCRIPTION
**Pull request by luke-hill**
Hi @mvz I cut a checkpoint roughly halfway between 1.0.alpha2 and the current master. And I've badged it as a 1.0.alpha.3

## Motivation and Context

Hopefully this gives us "some" of the newer code in a release so we can see how much of the newer stuff is working / not working.

Obviously the majority of stuff between 1.0.alpha2 and master is mainly test/dev tweaks, so I don't envision this will be "that" different too the 2nd alpha, but it includes a healthy amount of commits (Around 150-200).

Hopefully getting this cut and released will make the job of releasing a 4th alpha / stable 1.0 a bit easier, as we can see what stuff here works and what doesn't.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (cleanup of codebase without changing any existing functionality)
- [ ] Update documentation

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by luke-hill** [comment]
Obviously you can just cut a release mark against this branch and release the gem, or you can merge this directly into master if you'd prefer and cut it that way (But it's deliberately several hundred commits behind)

**Comment by mvz** [comment]
Why not release current master as alpha3?

**Comment by luke-hill** [comment]
I figured that there's been like 500 commits and that there probably should have been an interim release. I guess you could if you felt as though the likelihood is there wouldn't be lots of more issues that would come out. Whatever you think is easiest.

**Comment by mvz** [comment]
Ok, I'll try to get an alpha 3 out next weekend.

**Comment by luke-hill** [comment]
If there's any code cutting / tasks you want me to do fire them my way, rails doesn't have much and I've got a few outstanding PRs needing review from matt in ruby, so not much else I can do here

**Comment by mvz** [comment]
... and released it is :tada:!

**Pull request merged**
