### PR TITLE
Prepare release 0.14.3

### PR DESCRIPTION
**Pull request by mvz**
## Summary

Prepare release 0.14.3

## Details

Update History and version number

## Motivation and Context

Let's have a released version with up-to-date dependencies.

## Types of changes

- Version bump
- Update documentation

## Checklist:

- My change requires a change to the documentation.
- I have updated the documentation accordingly.

### CODE REVIEW

**Comment by olleolleolle** [comment]
LGTM!

**Comment by mvz** [comment]
I'll see if I can release tonight. Not sure I have rights but we'll see ...

**Comment by olleolleolle** [comment]
Having a `still` release with updated deps will be good!

**Comment by mvz** [comment]
I pushed the tag but can't push to rubygems.

**Pull request merged**
