### PR TITLE
Even more RuboCop cleanups

### PR DESCRIPTION
**Pull request by mvz**
## Summary

Process some to-dos from the RuboCop to-do file, and shorten the maximum line length.

## Details

* (Auto-)correct several items from the RuboCop to-do file
* Shorten the maximum line length to 95 and fix offending long lines

## Motivation and Context

Working toward a cleanly formatted code base.

## How Has This Been Tested?

Travis, although it seems to be having some issues lately.

## Types of changes

- Refactoring (cleanup of code base without changing any existing functionality)

### CODE REVIEW

**Comment by olleolleolle** [comment]
If Travis continues to be difficult, should we investigate alternate CI solutions?

**Comment by mvz** [comment]
> If Travis continues to be difficult, should we investigate alternate CI solutions?

Yes, that may be necessary.

**Comment by olleolleolle** [comment]
The current failure though, seems to have an ordinary reason: "can not find method `api`"

**Comment by mvz** [comment]
> The current failure though, seems to have an ordinary reason: "can not find method `api`"

No, that's a pending test, fortunately. Still, it's a distracting message that should be cleaned up.

**Pull request merged**
