### PR TITLE
Rakefile: wrap in bundle exec

### PR DESCRIPTION
**Pull request by olleolleolle**
- I am trying to make the Travis build run license_finder

### CODE REVIEW

**Comment by olleolleolle** [comment]
@maxmeyer Oh, my investigation was not final - and the license_finder still fails in Travis, trying to locate the right gems in the Gemfile.lock - https://travis-ci.org/cucumber/aruba/jobs/252143170#L340 is an example of that.

**Comment by maxmeyer** [comment]
There's another PR fixing a lot issues from @mvc.

**Comment by olleolleolle** [comment]
@maxmeyer Thanks for linking to that! It explains so much

**Comment by mvz** [comment]
This commit shouldn't be needed since AIUI, all `bundle exec` does is set some environment variables, and these will already be inherited from the outer level `bundle exec rake`.

**Comment by maxmeyer** [comment]
@mvc  You're right, I think that was the reason, why I didn't add it. but it doesn't do any harm for those using rake directly, right?

**Comment by mvz** [comment]
No, I don't think it does any harm.

**Pull request merged**
