### PR TITLE
Feature/root directory

### PR DESCRIPTION
**Pull request by dg-ratiodata**
PR based on comment from @jarl-dk on this PR #224.

### CODE REVIEW

**Comment by dg-ratiodata** [comment]
Failure no travis seems to be a bug in cucumber, see cucumber/cucumber#827 for this.

**Comment by dg-ratiodata** [comment]
rebased.

**Comment by dg-ratiodata** [comment]
@jarl-dk @mattwynne What about this one? This provides an helper to get the root directory of `aruba`. I used this helper in #224 to find the fixtures directory.

By default this is `Dir.getwd`. But using this directly is not enough because CWD can be changed by using [`cd`](https://github.com/cucumber/aruba/blob/master/lib/aruba/api.rb#L88) later on.

**Comment by dg-ratiodata** [comment]
Merged.

**Comment by mattwynne** [comment]
I know this is consistent with other configuration settings like `@aruba_io_wait_seconds` but it reminds me that I don't like this mechanism of configuration by setting instance variables. 

I'd like us to go over to using `Aruba.configure` for all this stuff.

**Comment by dg-ratiodata** [comment]
Sounds good. Something like `RSpec.configure`?

**Comment by mattwynne** [comment]
Yes, exactly like that. The [mechanism already exists](https://github.com/cucumber/aruba/blob/master/lib/aruba/config.rb#L37) in Aruba, but it's not used consistently.

**Comment by mattwynne** [comment]
Can you create a new ticket for that @maxmeyer?

**Comment by mattwynne** [comment]
Or should I say, @dg-ratiodata? ;)

**Comment by dg-ratiodata** [comment]
:-) Either is ok....

**Pull request closed without merging**
