### PR TITLE
README: Renamed default branch

### PR DESCRIPTION
**Pull request by olleolleolle**
## Summary

This is a start of "get the default branch name" used everywhere.

## Details

A name change was started, this keeps it going.

## Motivation and Context

It was mentioned in https://github.com/cucumber/common/issues/1507?#issuecomment-841312710

## How Has This Been Tested?

Not tested yet!

I searched, and found more places than this, but this is a start.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update
- [ ] Internal change (refactoring, test improvements, developer experience or update of dependencies)

## Checklist:

- [ ] I've added tests for my code
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by mvz** [comment]
Can you also adjust the GitHub actions, please? No build is triggered when merging, currently.

**Comment by mvz** [comment]
No build is triggered for pull requests, either. Really, this is all going in the wrong order :disappointed:

**Comment by mvz** [comment]
I'm going to go ahead and merge this. Then we can tackle the rest later.

**Comment by olleolleolle** [comment]
Sorry I was away from a big screen, hope things turn out OK!

**Comment by mvz** [comment]
Yes, everything seems to work now, thanks!

**Pull request merged**
